import "./globals.css";
import { SettingsProvider } from "@/context/SettingsContext";

export const metadata = {
  title: "Quran Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <SettingsProvider>
          {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
